### ISSUE TITLE
Just a few things

### ISSUE THREAD

**Issue by ahmad-511** [gitdagray/js_calculator_tut#1]
Hello Dave,
I found few things:

## CSS things:

In the `body` rule

- `background: #fff` should be `background-color: #fff;`
- Also, we can remove first gradient step `rgba(255, 255, 255, 1) 0%` since next step starts at 0%

In the ` .previousvalue` rule
- First time a number is displayed the div height expands, we can add `height: 1rem` to fix this

## JavaScript things:

- In the `deleteButton` event listener, after slicing the last number we must set `currentValue` to 0 

Fix:
```js
deleteButton.addEventListener('click', () => {
    const value = currentValueElem.value.slice(0, -1);
    currentValueElem.value = value? value: 0;
});
```

- In the `clearButtons` event listener, Error when re-assigning the constant `equationArray`
Fix:
Declare `equationArray` using `let` instead of `const`

- In the `equalsButton` event listener, Clicking `clearEntry` after clicking `equals` (`newNumberFlag == true`) doesn't clear `.previous`

Fix:
```js
if (event.target.classList.contains('clear')  || (event.target.classList.contains('clearEntry') && newNumberFlag)) {
    previousValueElem.textContent = '';
    itemArray = [];
    equationArray = [];
}
```

- In the `inputButtons` event listener, decimal point shouldn't be entered twice

Fix:
```js
if (newInput == '.' && currentValueElem.value.indexOf('.') > -1) {
    return;
}
```

Still investigating

**Comment by gitdagray** [comment]
Great stuff Ahmad! 

JS: Some little things I missed (delete button providing zero when the last character is gone and the 2 decimal entry) and the const vs let definition was a late addition with tired eyes as I decided to include the equationsArray in the clear button feature. The clear entry functions as it should which is to only delete the latest entry (currentvalue). The Windows 10 calculator does temporarily hide the history with CE, but it brings it back if you press equals again. 

I pushed these changes after reading your Youtube comment and before reading this. Our solutions both have the same result and it is interesting to compare as we chose different methods to achieve the same goals :) 

CSS: I'm going to leave the linear-gradient as is. It came straight from the linear-gradient generator and the background shorthand is acceptable. I like your idea for the 1rem height in the previousvalue class and will add it. 

Thanks again my friend!
