### ISSUE TITLE
Can't input 0.01

### ISSUE THREAD

**Issue by ahmad-511** [gitdagray/js_calculator_tut#2]
Hello again,

The problem is in `main.js` at line `21` in the ternary operator condition
When trying to type` 0.0` it's considered as `0` and passes the condition, `currentValueElem.value` will be then set to the `newInput` which is `0` which replaces the  `0.` we previously typed in

**Suggested fix:**
Update the condition at line 20 to consider the absence of the decimal point:
```js
currentValueElem.value == 0 && !currentValueElem.value.includes('.')
```

This will result in displaying `0.000` for example in the `previousValueElem` if entered as the very first number unlike Win 10 Calculator which displays it as `0`,

this can be fixed by `parseFloat(currentValueElem.value)` when reading `currentValue` on the `opButtons` event listener at line `39`

```js
const currentVal = parseFloat(currentValueElem.value);
```
Regards

**Comment by gitdagray** [comment]
This is a great catch Ahmad. Thanks! 

I went with your suggestion on line 39 for the parseFloat. 

Your suggestion for line 20 does not allow a leading 0 to remain as in 0.01 instead of .01. 

Windows does allow this leading zero, so I provided a similar solution to yours that keeps the leading zero: 

    currentValueElem.value == 0 && currentValueElem.value.length == 1 && newInput !== '.'

**Comment by ahmad-511** [comment]
That's a better solution,
I noticed the problem with the leading 0 but I didn't try to fix it.

Thanks Dave,
